# Generated by Django 4.2.7 on 2023-12-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimages',
            name='image_main',
        ),
        migrations.RemoveField(
            model_name='postimages',
            name='image_other',
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.FileField(default='blog/default.jpg', upload_to='blog/'),
        ),
        migrations.AddField(
            model_name='postimages',
            name='image',
            field=models.ImageField(default=1, upload_to='blog/'),
            preserve_default=False,
        ),
    ]
