# Generated by Django 4.2.7 on 2023-12-06 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostImages',
            new_name='PostImage',
        ),
    ]
