# Generated by Django 4.2.7 on 2023-12-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_postimages_postimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='content_1',
        ),
        migrations.AddField(
            model_name='post',
            name='content_2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
