# Generated by Django 4.2.7 on 2023-12-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_content_post_content_1_post_content_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_content_1',
            field=models.ImageField(default='blog/image_content.png', upload_to='blog/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_content_2',
            field=models.ImageField(default='blog/image_content.png', upload_to='blog/'),
        ),
    ]
