# Generated by Django 4.2.7 on 2023-12-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_image_content_1_post_image_content_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sub_title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
