# Generated by Django 4.2.7 on 2023-12-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_product_price_alter_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_age',
            field=models.IntegerField(blank=True),
        ),
    ]
