# Generated by Django 4.2.7 on 2023-12-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light_mode', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['created_date']},
        ),
        migrations.AddField(
            model_name='newsletter',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default='2023-12-10 17:21:22.501758'),
            preserve_default=False,
        ),
    ]
